FROM lukepighetti/pigeon-docker

EXPOSE 8757

CMD ["pigeond", \
  "-printtoconsole", \
  "-txindex", \
  "-rpcuser=rpc_user", \
  "-rpcpassword=rpc_password", \
  "-rpcport=8757", \
  "-rpcallowip=0.0.0.0/0"]